server.port=8080

spring.datasource.url=jdbc:h2:mem:jwt-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=4a6f686e446f6553656372657456657279566572795365637265744b6579466f724a57545369676e696e67
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
